### ISSUE TITLE
Dashboard remove

### ISSUE THREAD

**Issue by michalcerny** [itsthisjustin/HeliumLift#11]
Hey, dashboard of heliumlift hosted on duet.to is removed, can you somehow fix it? :)

**Comment by itsthisjustin** [comment]
Latest code should be on Bitballoon! Are you updated to the latest?

**Comment by michalcerny** [comment]
I have version 2.2 from appstore.

**Comment by itsthisjustin** [comment]
The latest update should point to a different url. I will check and upload a new copy if not.

**Comment by michalcerny** [comment]
Any progress? Dashboard still not working.

**Comment by itsthisjustin** [comment]
@thiscodeworks I just downloaded the latest copy from the app store and it's pointing to the correct URL. Have you tried deleting the app and redownloading?

**Comment by michalcerny** [comment]
Downloaded clean install to my second macbook and still showing "duet.to"

<img width="514" alt="screen shot 2018-02-12 at 19 25 38" src="https://user-images.githubusercontent.com/31419790/36112610-898abc1a-102a-11e8-8cb2-39f6cc329e46.png">

**Comment by olefrerichs** [comment]
same here. just deleted app - reinstalled from app store - seeing the same screen. Available Version is 2.2 Updated 9th Nov 2016 - can that be right?

**Comment by itsthisjustin** [comment]
Hey guys, I'll get this fixed and uploaded this week. I don't quite understand how this is possible, but I'm gonna get it fixed. Thanks for bringing it to my attention and apologize for the lack of speed on this end.

**Comment by olefrerichs** [comment]
No need to apologize, thank you a lot for your efforts! I'm enjoying this little handy tool almost on a daily basis! Thank you very much!!

**Comment by michalcerny** [comment]
@itsthisjustin Hey! Thanks for fixing it 👍 is there anyway to support chrome / safari extensions? Will love to have adblock in heliumlift and any optin to show/hide the heliumlift top bar to have only clean video view. Thank you Justin 👋

**Comment by itsthisjustin** [comment]
@thiscodeworks @olefrerichs fixed and available now in the app store!

**Comment by olefrerichs** [comment]
great! tested and works fine! thank you very much!
