### ISSUE TITLE
My Chrome extension also works with HeliumLift

### ISSUE THREAD

**Issue by gabrielbarros** [itsthisjustin/HeliumLift#12]
My Chrome extension also works with HeliumLift. You could link it in the readme, if you want.

https://chrome.google.com/webstore/detail/ekajjllcmeckibblgckgoceinmmgnfop

*PS.: you need to check the option "Open video with Helium on macOS" and select "HeliumLift" for Helium app.*

Thanks.

**Comment by itsthisjustin** [comment]
@gabrielbarros would be more than happy to add that to the readme. thanks!
