### ISSUE TITLE
Is this available outside the App Store?

### ISSUE THREAD

**Issue by haywirez** [itsthisjustin/HeliumLift#16]
I don't have an Apple ID and trying to keep it that way 😢

**Comment by itsthisjustin** [comment]
It used to be, but it was a pain to maintain. I can make you a build though. About to push a new update and I will sign a developer copy for you to install and upload it here.

**Comment by haywirez** [comment]
Wow, that's very kind of you! Thanks! 🤩

**Comment by itsthisjustin** [comment]
[HeliumLift.zip](https://github.com/itsthisjustin/HeliumLift/files/1895573/HeliumLift.zip)

**Comment by jtcreative** [comment]
Yes
