### ISSUE TITLE
Possible to edit Dashboard?

### ISSUE THREAD

**Issue by hellomrjones** [itsthisjustin/HeliumLift#24]
How can I edit the Dashboard? Is this a html file I can edit somewhere?

**Comment by itsthisjustin** [comment]
It's hardcoded unfortunately. You can obviously fork this repo though and change the URL to something on your end. Should be easy to find the URL in the code and rip down the HTML from it if you want to modify it. There's a huge update to this app pending but just been massively occupied by my startup.

**Comment by hellomrjones** [comment]
Thanks for the quick reply Justin. I thought so - I might look into it, although my programming days are long over. Good look with your Start Up and thanks for providing Helium Lift, which works better than the original on my end.
