### ISSUE TITLE
Chrome extension doesn't work

### ISSUE THREAD

**Issue by wvierber** [itsthisjustin/HeliumLift#3]
Just nothing happens when I want to sent a page to the app.

**Comment by itsthisjustin** [comment]
Odd. It's working fine on my end. Could be a permissions thing.

**Comment by wvierber** [comment]
Besides admin permissions, I believe, I blocked nothing.

**Comment by itsthisjustin** [comment]
This is fixed now

**Comment by ashrovy** [comment]
it doesn't work for me

**Comment by itsthisjustin** [comment]
@ashrovy I will take a look
