### ISSUE TITLE
Shortcuts aren't working

### ISSUE THREAD

**Issue by wvierber** [itsthisjustin/HeliumLift#4]
Even cmd + v doesn't work when I want to enter an URL.

Can this be caused because of HeliumLift isn't seen as a 'real' application? You can't cmd+tab to the app (see image). With the original Helium, this is possible, shortcuts work.

Even quitting the app sometimes doen't work... (without shortcut)

![image](https://cloud.githubusercontent.com/assets/12418372/9468145/2c8e93da-4b40-11e5-9ed2-031aafaa082a.png)

**Comment by itsthisjustin** [comment]
That's a very interesting observation. I'll definitely look into that. Should be simple to fix.

**Comment by itsthisjustin** [comment]
Fixed in the latest version
